# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SS3D
email: RESS3D.project@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a 3D recreation of Space Station 13, on the Unity engine,
  which will come with its own set of gameplay/graphical improvements. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ss3d.space" # the base hostname & protocol for your site, e.g. http://example.com
discord_url: https://discord.gg/3ny9tdH
github_url: https://github.com/RE-SS3D
gitbook_url: https://ss3d.gitbook.io/
google_drive_url: https://drive.google.com/drive/folders/16WCAVGAE_lPYF5l9avK2C0o045xNx0zI?usp=sharing
trello_url: https://trello.com/ress3d
reddit_url: https://reddit.com/r/RESS3D
youtube_url: https://www.youtube.com/@spacestation3d
twitter_url: https://twitter.com/SpaceStation3D
paypal_url: https://www.paypal.me/SpaceStation3D
patreon_url: https://www.patreon.com/ss3d
subscribestar_url: https://www.subscribestar.com/space-station-3d
google_analytics: UA-140169746-1

# Build settings
markdown: kramdown
plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: 'https://api.github.com/orgs/RE-SS3D/repos'
    cache: false
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-responsive-image
responsive_image:
  #template: _includes/responsive-image.html
  template: _includes/srcset-split.html
  sizes:
    - width: 580  # [Required] How wide the resized image will be.
    - width: 290
    - width: 170
    - width: 145
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
